### ISSUE TITLE
Sir,I face a problem when  training

### ISSUE THREAD

**Issue by csuquan** [dgriffiths3/ml_segmentation#1]
[INFO] Reading image data.
[INFO] Creating training dataset on 3 image(s).
[INFO] Computing local binary pattern features.
[INFO] Computing haralick features.
Traceback (most recent call last):=======================================] 100%
  File "train.py", line 229, in <module>
    main(image_dir, label_dir, classifier, output_model)
  File "train.py", line 217, in main
    X_train, X_test, y_train, y_test = create_training_dataset(image_list, label
_list)
  File "train.py", line 161, in create_training_dataset
    features, labels = create_features(img, img_gray, label_list[i])
  File "train.py", line 143, in create_features
    label = label[h_ind:-h_ind, h_ind:-h_ind]
**TypeError: 'NoneType' object is not subscriptable**

what should I do ?

-------------------------------------------------------------------------------------------------------
I solved this problem by changing some codes in train.py form 49 line -53 line
here is my changes:
```
    for file in filelist:

        image_list.append(cv2.imread(file, 1))


    filelist2 = glob(label_dir + '/*.png')

    for file in filelist2:

        label_list.append(cv2.imread(file, 0))
```

**Comment by csuquan** [comment]
I solved the problem but face another~

Traceback (most recent call last):=======================================] 100%
  File "train.py", line 237, in <module>
    main(image_dir, label_dir, classifier, output_model)
  File "train.py", line 225, in main
    X_train, X_test, y_train, y_test = create_training_dataset(image_list, label
_list)
  File "train.py", line 168, in create_training_dataset
    features, labels = create_features(img, img_gray, label_list[i])
  File "train.py", line 151, in create_features
    labels = label.reshape(label.shape[0]*label.shape[1], 1)
ValueError: cannot reshape array of size 1044300 into shape (348100,1)

**Comment by igor-morawski** [comment]
The error is in
label_list.append(cv2.imread(label_dir+"/"+file.split("/")[-1].split('.')[0]+'.png', 0))
for Windows this string should be split with \\\\

**Comment by dgriffiths3** [comment]
@mo-igor Using '/' is for linux and mac filesystems and as such is not compatible with windows. I've changed the code to now use the OS package which should work for both windows and linux based systems. I don't have a windows machine to test, so please let me know if this still doesn't work.
