### ISSUE TITLE
Inference is very slow

### ISSUE THREAD

**Issue by vs-ai** [dgriffiths3/ml_segmentation#2]
Thank you for the clean code!

Training goes fine; however, on inference it takes dozens of minutes to compute the result for a single image. The Haralick feature computation is very very slow.

**Comment by dgriffiths3** [comment]
@vs-ai i yes it's very slow indeed. I created this originally to benchmark against a CNN. I imagine it could be made faster by implementing multi-thread processing as each haralick feature vector is independent of each other. I don't have the time at the moment to do this, but will as soon as I do.

**Comment by mserouar** [comment]
Hi !

Have you try to use XGboost on the RandomForestClassifier ?
