### ISSUE TITLE
generalisation on unseen data

### ISSUE THREAD

**Issue by pamparana34** [dgriffiths3/ml_segmentation#6]
I trained this on my own data of around ~ 500 images and it is performing really badly on unseen data (low generalisation). Can you comment on whether the segmented images you show in the repo description are training or unseen test images?

**Comment by dgriffiths3** [comment]
The images I showed were on unseen images for the README. I would imagine the results would not be excellent on unseen data, but should still make sense. If they are basically random there will likely be an error in the way you process the data.
